obj-m := scheduler.o
KDIR := /lib/modules/4.15.0-42-generic/build/
PWD := $(shell pwd)
MY_CFLAGS += -g -DDEBUG -z execstack


defualt:
	$(MAKE) -C $(KDIR) SUBDIRS=$(PWD) modules

debug:
	make -C $(KDIR) SUBDIRS=$(PWD) modules EXTRA_CFLAGS="$(MY_CFLAGS)"

clean:
	rm -rf *.ko
	rm -rf *.mod.*
	rm -rf .*.cmd
	rm -rf *.o
	rm -rf *~
	rm -rf *.order
	rm -rf *.symvers
